service: aws-biling-alert

frameworkVersion: ">=3 <4"

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 128
  timeout: 6
  region: ${env:AWS_REGION, "us-east-1"}
  logRetentionInDays: 7
  stage: v1
  environment:
    # required
    SLACK_INCOMING_WEBHOOK_URL: ${env:SLACK_INCOMING_WEBHOOK_URL}
    # options
    COST_REPORT_THRESHOLDS: ${env:COST_REPORT_THRESHOLDS, self:custom.defaultThreasholds}
    MESSAGE_FOR_EXCESSIVE_USAGE: ${env:MESSAGE_FOR_EXCESSIVE_USAGE, self:custom.defaultMessageForExcessiveUsage}
    MESSAGE_FOR_MONTHLY_REPORT: ${env:MESSAGE_FOR_MONTHLY_REPORT, self:custom.defaultMessageForMonthlyReport}
    MESSAGE_NO_COST_DATA: ${env:MESSAGE_NO_COST_DATA, self:custom.defaultMessageNoCostData}
    SLACK_CHANNEL: ${env:SLACK_CHANNEL, self:custom.defaultSlackChannel}
    SLACK_USERNAME: ${env:SLACK_USERNAME, self:custom.defaultSlackUsername}
    SLACK_EMOJI: ${env:SLACK_EMOJI, self:custom.defaultSlackEmoji}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cloudwatch:GetMetricData
          Resource:
            - "*"

custom:
  defaultThreasholds:
    Fn::Join:
      - ","
      - - 5
        - 300
        - 1000
  defaultMessageForExcessiveUsage: "<!channel> The AWS usage fee for this month has exceeded over %s USD."
  defaultMessageForMonthlyReport: "<!channel> The AWS usage fee for last month is %s USD."
  defaultMessageNoCostData: "<!channel> There is no cost data for this month."
  defaultSlackChannel: "#general"
  defaultSlackUsername: "AWS Billing Bot"
  defaultSlackEmoji: ":ghost:"

package:
  patterns:
    - '!socials/**'
    - '!README.md'
    - '!package.json'
    - '!yarn.lock'
    - '!package-lock.json'

functions:
  daily:
    handler: src/daily.handler
    events:
      - schedule: cron(0 4 * * ? *)

  monthly:
    handler: src/monthly.handler
    events:
      - schedule: cron(0 4 1 * ? *)
